spring:
    application:
        name: discovery
 
eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false
        fetch-registry: true
        registryFetchIntervalSeconds: 10
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/

server:
    port: 8082