spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 10

zuul:
  routes:
    discovery:
      path: /discovery/**
      url: http://localhost:8082
    book-service:
      path: /book-service/**
      url: http://localhost:8085
    rating-service:
      path: /rating-service/**
      url: http://localhost:8086