spring:
  application:
    name: gateway-service

server:
  port: 8080

zuul:
  routes:
    discovery:
      path: /discovery/**
      url: http://localhost:8082
    book-service:
      path: /book-service/**
      url: http://localhost:8085