spring:
  application:
    name: config-service
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IbrayevRamil/trying-spring-cloud
          search-paths: config-storage

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    region: default
    registry-fetch-interval-seconds: 5
